// countries.js
const countries = [
  {
    id: 1,
    name: "Germany",
    population: 81770900,
    region: "Europe",
    capital: "Berlin",
    borders: [
      "Denmark",
      "Poland",
      "Czechia",
      "Austria",
      "Switzerland",
      "France",
      "Luxembourg",
      "Belgium",
      "Netherlands",
    ],
    languages: ["German"],
    flag: "./img/Germany.svg",
  },
  {
    id: 2,
    name: "United States of America",
    population: 323947000,
    region: "Americas",
    capital: "Washington, D.C.",
    borders: ["Canada", "Mexico"],
    languages: ["English"],
    flag: "./img/USA.svg",
  },
  {
    id: 3,
    name: "Brazil",
    population: 206135893,
    region: "Americas",
    capital: "Brasília",
    borders: [
      "French Guiana (France)",
      "Suriname",
      "Guyana",
      "Venezuela",
      "Colombia",
      "Peru",
      "Bolivia",
      "Paraguay",
      "Argentina",
      "Uruguay",
    ],
    languages: ["Portuguese"],
    flag: "img/Brazil.svg",
  },
  {
    id: 4,
    name: "Iceland",
    population: 334300,
    region: "Europe",
    capital: "Reykjavík",
    borders: [],
    languages: ["Icelandic"],
    flag: "img/white-plus.svg",
  },
  {
    id: 5,
    name: "Afghanistan",
    population: 27657145,
    region: "Asia",
    capital: "Kabul",
    borders: [
      "Pakistan",
      "Iran",
      "Turkmenistan",
      "Uzbekistan",
      "Tajikistan",
      "China",
    ],
    languages: ["Pashto", "Dari (Persian)"],
    flag: "./img/dubai.svg",
  },
  {
    id: 6,
    name: "Åland Islands",
    population: 28875,
    region: "Europe",
    capital: "Mariehamn",
    borders: [],
    languages: ["Swedish"],
    flag: "img/plus.svg",
  },
  {
    id: 7,
    name: "Albania",
    population: 2886026,
    region: "Europe",
    capital: "Tirana",
    borders: ["Montenegro", "Kosovo", "North Macedonia", "Greece"],
    languages: ["Albanian"],
    flag: "img/smth.svg",
  },
  {
    id: 8,
    name: "Algeria",
    population: 40400000,
    region: "Africa",
    capital: "Algiers",
    borders: [
      "Tunisia",
      "Libya",
      "Niger",
      "Mali",
      "Mauritania",
      "Western Sahara",
      "Morocco",
    ],
    languages: ["Arabic", "Berber (Tamazight)"],
    flag: "img/Tadjikistan.svg",
  },
];

export default countries;